# Homework 3
## Li Zheng

##  Problem 1: Vectors and Coordinate systems<br>
 Let {**g<sub>i</sub>**}<sub>i=1,2,3</sub>, or **g<sub>1**,**g<sub>2**,**g<sub>3**, be the unit orthogonal basis vectors of the global coordinate system. Now,we define the new local coordinate system using the basis vectors {**e<sub>i</sub>**}<sub>i=1,2,3</sub>, or **e<sub>1**,**e<sub>2**,**e<sub>3**,as follows:<br>
<center>**e<sub>1</sub>** = −0.41166073 **g<sub>1</sub>** - 0.46269725 **g<sub>2</sub>** + 0.78514119 **g<sub>3</sub>** <br>
**e<sub>2</sub>** = −0.0485159** g<sub>1</sub>** − 0.8491783 **g<sub>2</sub>** − 0.52587301 **g<sub>3</sub>** <br>
**e<sub>3</sub>** = 0.91004486 **g<sub>1</sub>** − 0.2545731 **g<sub>2</sub>** + 0.32712518 **g<sub>3</sub>** <br>
</center>Answer the following questions, and submit the solution as jupyter notebooks with markdowns.

In [34]:
import numpy as np
import matplotlib.pyplot as plt

a) Check that the basis vectors for the local coordinate system **e<sub>1**,**e<sub>2**,**e<sub>3** are unit orthogonal basis vectors.

<font color="blue">In the following codes, the function 'unit_orthogonal_check' calculates the magnitude and dot product. If the magnitude of the targetted system equals 1 and the dot product of the system equals 0, the coordinate system are unit orthogonal basis vector and the code will print 'True'. Or they are not orthogonal basis vectors, and the code will print 'False' after running.

In [35]:
def approximation(value, setted, tolerance=1e-6):
    return abs(value - setted) > tolerance

class Problem1:
    def __init__(self,e,g):
        self.e = e
        self.g = g
    def unit_orthogonal_check(self,e):
        check = True
        for i in range(3):
            for j in range(i+1,3):
                dot_product=np.dot(e[i],e[j])
                norm = np.linalg.norm(e[i])
                if approximation(norm, 1) or approximation(dot_product, 0) :
                    print (i,j)
                    print (approximation(norm, 1),approximation(dot_product, 0) )
                    check = False
        return check
    
    # tranform the global coordiante expression to local coordinate expression
    def get_transform(self,e,g):
        g = [g_1,g_2,g_3]
        T = np.zeros((3,3))
        for i in range(3):
            for j in range(3):
                if isinstance(self.e[i], np.ndarray) and isinstance(g[j], np.ndarray):
                    T[i, j] = np.dot(self.e[i], g[j])
                    #print (T[i,j])
                else:
                    raise ValueError("Arrays expected.")
                #T[i+3,j+3]= np.dot(self.e[i],g[j])
        return T

<font color="blue">After setting the function, we put the known data into the function and run it for checking.

In [36]:
e_1=np.array([-0.41166073, -0.46269725,  0.78514119])
e_2=np.array([-0.0485159,  -0.8491783,  -0.52587301])
e_3=np.array([ 0.91004486, -0.2545731,   0.32712518])

g_1=np.array([1,0,0])
g_2=np.array([0,1,0])
g_3=np.array([0,0,1])

e = [e_1,e_2,e_3]
g = [g_1,g_2,g_3]

hw = Problem1(e,g)
hw.unit_orthogonal_check(e)

True

<font color="blue"> From the check, we could know that the vectors in the local coordinate system are unit and orthogonal vecotrs.

<br>
b) Express the vector <b>e<sub>1</sub></b>,<b>e<sub>2</sub></b>,<b>e<sub>3</sub></b>  by components using two different coordinate systems, local coordinate system ({<b>e<sub>i</sub></b>}) and global coordiante system ({<b>g<sub>i</sub></b>}).

<font color="blue">The **e<sub>1**,**e<sub>2**,**e<sub>3** expressed in local coordinate system remains with its original parameters, while the function for tranforming the vectors in local coordinate system to global coordinate system is supposed to be coded. The codes are shown along with the codes in a). Here, we set T as the transforming matrix for vectors in local coordinate system, and apply the data.

In [37]:
T=hw.get_transform(e,g)
np.set_printoptions(suppress=True, precision=8)

vector_l = [np.array([1,0,0]), np.array([0,1,0]), np.array([0,0,1])]

vector_local = np.around(vector_l, decimals=8)
vector_global = np.around(T @vector_l, decimals=8)
print("e_1,e_2,e_3 (local): ")
print (vector_local)
print("e_1,e_2,e_3 (global): ")
print (vector_global)

e_1,e_2,e_3 (local): 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
e_1,e_2,e_3 (global): 
[[-0.41166073 -0.46269725  0.78514119]
 [-0.0485159  -0.8491783  -0.52587301]
 [ 0.91004486 -0.2545731   0.32712518]]


<br>
c) Express the vectors <b>g<sub>1</sub></b>,<b>g<sub>2</sub></b>,<b>g<sub>3</sub></b>  by components using two different coordinate systems,local coordinate system ({<b>e<sub>i</sub></b>}) and global coordiante system ({<b>g<sub>i</sub></b>}).

<font color="blue">The **g<sub>1**,**g<sub>2**,**g<sub>3** expressed in global coordinate system remains with its original parameters.The function for tranforming the vectors in global coordinate system to local coordinate system is supposed to be coded. While, since the matrix with the function is the inverse matrix in b). So, we could directly apply the data to the inv_T.

In [38]:
T=hw.get_transform(e,g)
vector_g = [np.array([1,0,0]), np.array([0,1,0]), np.array([0,0,1])]
vector_local= np.around(T.T@vector_g, decimals=8)
vector_global = np.around(vector_g, decimals=8)
print("g_1,g_2,g_3 (local): ")
print (vector_local)
print("g_1,g_2,g_3 (global): ")
print (vector_global)
print (vector_local @ e)

g_1,g_2,g_3 (local): 
[[-0.41166073 -0.0485159   0.91004486]
 [-0.46269725 -0.8491783  -0.2545731 ]
 [ 0.78514119 -0.52587301  0.32712518]]
g_1,g_2,g_3 (global): 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 1.         -0.         -0.        ]
 [-0.          0.99999999  0.00000001]
 [-0.          0.00000001  0.99999999]]


<br>
d) Now, we define a new vector <b>v</b> as <br>
<center><b>v</b> = 0.5 <b>g<sub>1</sub></b> +  1.0 <b>g<sub>2</sub></b> +  1.5 <b>g<sub>2</sub></b> 
</center>Express the vector <b>v</b>  by components using two different coordinate systems, local coordinate system ({<b>e<sub>i</sub></b> }) and global coordiante system ({<b>g<sub>i</sub></b> }).

<font color="blue">The vector is defined in global coordinate system, so we could apply the method in c), then apply the data.

In [14]:
T=hw.get_transform(e,g)
v_g = np.array([0.5,1.0,1.5])
v_local = np.around(T@ v_g, decimals=8)
v_global = np.around(v_g, decimals=8)
print("v(local): ")
print (v_local)
print("v(global): ")
print (v_global)

v(local): 
[ 0.50918417 -1.66224576  0.6911371 ]
v(global): 
[0.5 1.  1.5]


<font color="blue">The last step is to check if the transformation is right. Here, I use magnitudes of the <b>v</b> in different coodinate systems as reference.

In [15]:
print (np.linalg.norm(v_local))
print (np.linalg.norm(v_global))
print (v_local @ e)

1.8708286871365258
1.8708286933869707
[0.49999999 1.         1.49999999]


<font color="blue">The magnitudes of <b>v</b> keeps the same, so it is right.

## Problem 2: Tensors
In this problem, we consider the basis vectors defined in problem 1 and a tensor <b>T</b> that does not change the original vector (remember that the tensor is an object that operates on a vecotr to product another vector). In other words, for an vectro <b>v</b>, <br>
<center><b>v</b> = <b> T v </b>
</center> Answer the following questions, and submit the solution as jupyter notebooks with markdowns.

In [17]:
import numpy as np
import matplotlib.pyplot as plt

a) Express the tensor <b>T</b> by component (matrix) if we measure both the input and output of the tensor operations using the global coordinate system {<b>g<sub>i</sub></b> }.

In [18]:
class Problem2:

    def __init__(self,e,g):
        self.e = e
        self.g = g
    
    def get_transform(self,g):
        g = [g_1,g_2,g_3]
        T = np.zeros((3,3))
        for i in range(3):
            for j in range(3):
                if isinstance(self.e[i], np.ndarray) and isinstance(g[j], np.ndarray):
                    T[i, j] = np.dot(self.e[i], g[j])
                    #print (T[i,j])
                else:
                    raise ValueError("Arrays expected.")
                #T[i+3,j+3]= np.dot(self.e[i],g[j])
        return T

<font color="blue"> Since <b>T</b> satisfaces that <br>
<center><font color="blue"><b>v</b> = <b> T v </b>
</center><font color="blue"> for any <b>v</b>, it is supposed to be a 3*3 unit matrix.

In [1]:
e_1=np.array([-0.41166073, -0.46269725,  0.78514119])
e_2=np.array([-0.0485159,  -0.8491783,  -0.52587301])
e_3=np.array([ 0.91004486, -0.2545731,   0.32712518])

g_1=np.array([1,0,0])
g_2=np.array([0,1,0])
g_3=np.array([0,0,1])

e = [e_1,e_2,e_3]
g = [g_1,g_2,g_3]

hw = Problem2(e,g)
T=hw.get_transform(g)

T_a = [np.array([1,0,0]), np.array([0,1,0]), np.array([0,0,1])]
print (T_a)

NameError: name 'np' is not defined

<br>
b) Expression the tensor <b>T</b> by component (matrix) if we measure the input and output of the tensor operation using the local coordinate system {<b>e<sub>i</sub></b> }.

<font color="blue"> In the problem, we mainly focuse on the transformation between local and global coordinates. The first step is to define the function 'get_transform' in the codes in a), which could transform the vector from global coordinate system to local coordinate system.<br>
Here, <b>T</b> is supposed to first transformed the <b>v</b> to global and then return back to local after proceeding T in a).<br>
From another view, the T remains the 3*3 unit matrix in local coordinate as well.

In [20]:
T_b = T @ T_a @ T.T
print (T_b)

[[ 0.99999999 -0.00000001 -0.00000001]
 [-0.00000001  1.          0.        ]
 [-0.00000001  0.          0.99999999]]


<br>
c) Express the tensor <b>T</b> by component (matrix) if we measure the input by the global coordinate system {<b>g<sub>i</sub></b> }, and measure the output by the local coordinate system {<b>e<sub>i</sub></b> }.

<font color="blue"><b>T</b> in a) could transform <b>v</b> from global coordinate system to local coordinate system. So here, we should first apply the <b>T_a</b> and tranform it to local. And the tranforming process is concluded in <b>T_c</b> as well.

In [21]:
T_c =  T.T @ T_a 
print (T_c)

[[-0.41166073 -0.0485159   0.91004486]
 [-0.46269725 -0.8491783  -0.2545731 ]
 [ 0.78514119 -0.52587301  0.32712518]]


<br>
d) Express the tensor <b>T</b> by component (matrix) if we measure the input by the local coordinate system {<b>e<sub>i</sub></b>}, and measure the output by the global coordinate system {<b>g<sub>i</sub></b>}.

<font color="blue">The inverse matrix of <b>T</b> in a) could transform <b>v</b> from local coordinate system to global coordinate system. So here, we should first apply the <b>T_a</b> and tranform it to local. And the tranforming process is concluded in <b>T_d</b> as well.

In [22]:
T_d = T @ T_b
print (T_d)

[[-0.41166073 -0.46269724  0.78514119]
 [-0.04851589 -0.8491783  -0.52587301]
 [ 0.91004485 -0.2545731   0.32712517]]


<br>
e) Express the tensor <b>T'</b> by components (matrix) if we measure both the input and output by the local coordinate system {<b>e<sub>i</sub></b>}.

<font color="blue">The tensor <b>T'</b> stretche <b>v</b> is <b>e<sub>2</sub></b> in local coordinate. So in the local coordinate system, it is defined as below:

In [23]:
T_e = [np.array([1,0,0]), np.array([0,2,0]), np.array([0,0,1])]
print (T_e)

[array([1, 0, 0]), array([0, 2, 0]), array([0, 0, 1])]


<br>
f) Express the tensor <b>T'</b> by components (matrix) if we measure both the input and output by the global coordinate system {<b>g<sub>i</sub></b>}.

<font color="blue">Since tensor <b>T'_e</b> is defined in local coordinate system, so in f), <b>T'_f</b> is supposed to include the tranforming process that tranform the input <b>v</b> in global coordinate system to local one, and tranform the output back to be in global coordinate system. The tranforming function is define in a).

In [24]:
T_f = T.T @ T_e @ T
print (T_f)

[[1.00235379 0.04119865 0.0255132 ]
 [0.04119865 1.72110378 0.44655996]
 [0.0255132  0.44655996 1.27654242]]


<br>
g) Apply the tensor to the vector v defined in problem 1(d), and express he results by components using global coordinate system {<b>g<sub>i</sub></b>}.

<font color="blue">The condition is as the same as the one in f). So we could simply apply the known vector <b>v</b> to the tensor in f).

In [25]:
v_g = np.array([0.5,1.0,1.5])
v_output = T_f  @ v_g
print (v_output)

[0.58064534 2.41154304 2.37413018]


<font color="blue">Check if the output satisfise the conditions.

In [32]:
print (T @ v_g)
print (T @ v_output)

[ 0.50918417 -1.66224576  0.6911371 ]
[ 0.50918418 -3.32449153  0.69113708]
